name: Publish

on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: node test/index.js

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: aspiesoft
      - run: npm publish
        env:
          AUTHOR_EMAIL: aspiesoftweb@gmail.com
          AUTHOR_NAME: aspiesoft
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: aspiesoft
      - name: scope
        run: npm publish --access public
        if: success()
      - name: noscope
        run: |
          sed -i 's+"@aspiesoft/+"+g' package.json
          sed -i 's+"@aspiesoft/+"+g' package-lock.json
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
