name: Publish

on:
  release:
    types: [published]
  push:
    branches:
      - master

strategy:
  fail-fast: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: node test/index.js

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: aspiesoft
      - run: npm publish
        if: failure()
      - run: exit 0
        env:
          AUTHOR_EMAIL: aspiesoftweb@gmail.com
          AUTHOR_NAME: aspiesoft
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: aspiesoft
      - run: npm publish --access public
        if: failure()
      - run: exit 0
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-npm-noscope:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: aspiesoft
      - run: sed -i 's+"@aspiesoft/+"+g' package.json
      - run: sed -i 's+"@aspiesoft/+"+g' package-lock.json
      - run: npm publish --access public
        if: failure()
      - run: exit 0
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
